name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Format
        run: cargo fmt --check
      - name: Test
        run: cargo test
      - name: Build
        run: cargo build

  servo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build with Servo feature flag
        env:
          BRAZEN_SERVO_SOURCE: vendor/servo
        run: cargo build --features servo
